"""
Opta event-CSV column lists for the published per-match parquets.

OPTA_EVENT_COLUMNS   — full header of the Opta event CSVs (pipeline/convert.py),
                       in file order. Every season 2021/22 → 2026/27 has exactly
                       these 248 columns.
MATCH_EVENT_COLUMNS  — the subset the Match Analysis modules read (108). Only
                       these are stored in data/match_events/.

Guarded by tests/test_match_events.py: every Opta column name referenced as a
string literal by a module reachable from the Match Analysis entry points must
be listed in MATCH_EVENT_COLUMNS. If that test fails after an analytics change,
add the column here and re-export the published seasons
(python -m src.utils.match_events export --force --season ...).
"""

OPTA_EVENT_COLUMNS: tuple[str, ...] = (
    'general_id',
    'event_id',
    'event',
    'type_id',
    'period_id',
    'time_min',
    'time_sec',
    'contestant_id',
    'team_name',
    'team_code',
    'team_position',
    'player_id',
    'player_name',
    'x',
    'y',
    'outcome',
    'timeStamp',
    'lastModified',
    'match_id',
    'coverage_level',
    'local_date',
    'local_time',
    'week',
    'number_of_periods',
    'period_length',
    'description',
    'represented_qualifiers',
    'non_represented_qualifiers',
    'Long ball',
    'Cross',
    'Head pass',
    'Through ball',
    'Free kick taken',
    'Corner taken',
    'Players caught offside',
    'Goal disallowed',
    'Penalty',
    'Hand',
    '6-seconds violation',
    'Dangerous play',
    'Foul',
    'Last line',
    'Head',
    'Small box-centre',
    'Box-centre',
    'Out of box-centre',
    '35+ centre',
    'Right footed',
    'Other body part',
    'Regular play',
    'Fast break',
    'Set piece',
    'From corner',
    'Free kick',
    'Unnamed: 54',
    'own goal',
    'Assisted',
    'Involved',
    'Yellow Card',
    'Second yellow',
    'Red Card',
    'Referee abuse',
    'Argument',
    'Fight',
    'Time wasting',
    'Excessive celebration',
    'Crowd interaction',
    'Other reason',
    'Injury',
    'Tactical',
    'Player Position',
    'Temperature',
    'Conditions',
    'Field Pitch',
    'Lightings',
    'Attendance figure',
    'Official position',
    'Official Id',
    'Injured player id',
    'End cause',
    'Related event ID',
    'Zone',
    'End type',
    'Jersey Number',
    'Small box-right',
    'Small box-left',
    'Box-deep right',
    'Box-right',
    'Box-left',
    'Box-deep left',
    'Out of box-deep right',
    'Out of box-right',
    'Out of box-left',
    'Out of box-deep left',
    '35+ right',
    '35+ left',
    'Left footed',
    'Left',
    'High',
    'Right',
    'Low Left',
    'High Left',
    'Low Centre',
    'High Centre',
    'Low Right',
    'High Right',
    'Blocked',
    'Close Left',
    'Close Right',
    'Close High',
    'Close Left and High',
    'Close Right and High',
    'High claim',
    '1 on 1',
    'Deflected save',
    'Dive and deflect',
    'Catch',
    'Dive and catch',
    'Def block',
    'Back pass',
    'Corner situation',
    'Direct free',
    'Six Yard Blocked',
    'Saved Off Line',
    'Goal Mouth Y Coordinate',
    'Goal Mouth Z Coordinate',
    'Attacking Pass',
    'Throw In',
    'Volley',
    'Overhead',
    'Half Volley',
    'Diving Header',
    'Scramble',
    'Strong',
    'Weak',
    'Rising',
    'Dipping',
    'Lob',
    'One Bounce',
    'Few Bounces',
    'Swerve Left',
    'Swerve Right',
    'Swerve Moving',
    'Keeper Throw',
    'Goal Kick',
    'Direction of play',
    'Punch',
    'Team Formation',
    'Team Player Formation',
    'Dive',
    'Deflection',
    'Far Wide Left',
    'Far Wide Right',
    'Keeper Touched',
    'Keeper Saved',
    'Hit Woodwork',
    'Own Player',
    'Pass End X',
    'Pass End Y',
    'Deleted Event Type',
    'Formation slot',
    'Blocked X Coordinate',
    'Blocked Y Coordinate',
    'Not past goal line',
    'Intentional Assist',
    'Chipped',
    'Lay-off',
    'Launch',
    'Persistent Infringement',
    'Foul and Abusive Language',
    'Throw In set piece',
    'Encroachment',
    'Leaving field',
    'Entering field',
    'Spitting',
    'Professional foul',
    'Handling on the line',
    'Out of play',
    'Flick-on',
    'Leading to attempt',
    'Leading to goal',
    'Rescinded Card',
    'No impact on timing',
    'Parried safe',
    'Parried danger',
    'Fingertip',
    'Caught',
    'Collected',
    'Standing',
    'Diving',
    'Stooping',
    'Reaching',
    'Hands',
    'Feet',
    'Dissent',
    'Blocked cross',
    'Scored',
    'Saved',
    'Missed',
    'Player Not Visible',
    'From shot off target',
    'Off the ball foul',
    'Block by hand',
    'Captain',
    'Pull Back',
    'Switch of play',
    'Team kit',
    'GK hoof',
    'Gk kick from hands',
    'Referee stop',
    'Referee delay',
    'Weather problem',
    'Crowd trouble',
    'Fire',
    'Object thrown on pitch',
    'Spectator on pitch',
    'Awaiting officials decision',
    'Referee Injury',
    'Game end',
    'Assist',
    'Overrun',
    'Length',
    'Angle',
    'Big Chance',
    'Individual Play',
    '2nd related event ID',
    '2nd assisted',
    '2nd assist',
    'Players on both posts',
    'Player on near post',
    'Player on far post',
    'No players on posts',
    'Inswinger',
    'Outswinger',
    'Straight',
    'Suspended',
    'Resume',
    'Own shot blocked',
    'Post match complete',
    'competition_id',
    'competition_name',
    'competition_known_name',
    'competition_sponsor_name',
    'competition_code',
    'venue_id',
    'venue_long_name',
    'formation',
    'position',
)

MATCH_EVENT_COLUMNS: tuple[str, ...] = (
    'event_id',
    'event',
    'type_id',
    'period_id',
    'time_min',
    'time_sec',
    'contestant_id',
    'team_name',
    'team_position',
    'player_name',
    'x',
    'y',
    'outcome',
    'timeStamp',
    'match_id',
    'week',
    'Long ball',
    'Cross',
    'Head pass',
    'Through ball',
    'Free kick taken',
    'Corner taken',
    'Penalty',
    'Foul',
    'Head',
    'Small box-centre',
    'Box-centre',
    'Out of box-centre',
    '35+ centre',
    'Right footed',
    'Fast break',
    'Set piece',
    'From corner',
    'Free kick',
    'own goal',
    'Second yellow',
    'Red Card',
    'Related event ID',
    'Small box-right',
    'Small box-left',
    'Box-deep right',
    'Box-right',
    'Box-left',
    'Box-deep left',
    'Out of box-deep right',
    'Out of box-right',
    'Out of box-left',
    'Out of box-deep left',
    '35+ right',
    '35+ left',
    'Left footed',
    'Left',
    'High',
    'Right',
    'Low Left',
    'High Left',
    'Low Centre',
    'High Centre',
    'Low Right',
    'High Right',
    'Blocked',
    '1 on 1',
    'Corner situation',
    'Direct free',
    'Saved Off Line',
    'Goal Mouth Y Coordinate',
    'Goal Mouth Z Coordinate',
    'Attacking Pass',
    'Throw In',
    'Volley',
    'Strong',
    'Weak',
    'Rising',
    'Dipping',
    'Swerve Left',
    'Swerve Right',
    'Goal Kick',
    'Deflection',
    'Hit Woodwork',
    'Pass End X',
    'Pass End Y',
    'Blocked X Coordinate',
    'Blocked Y Coordinate',
    'Chipped',
    'Lay-off',
    'Launch',
    'Throw In set piece',
    'Flick-on',
    'Leading to attempt',
    'Leading to goal',
    'Pull Back',
    'Switch of play',
    'GK hoof',
    'Gk kick from hands',
    'Assist',
    'Length',
    'Angle',
    'Big Chance',
    'Individual Play',
    'Players on both posts',
    'Player on near post',
    'Player on far post',
    'No players on posts',
    'Inswinger',
    'Outswinger',
    'Straight',
    'formation',
    'position',
)
