"""
Player Analysis — Single-Match, Both-Teams Player Metrics
==========================================================
Analytics engine for the **Player Analysis** module inside Match Analysis.

Unlike the other Match Analysis phases (Offensive / Defensive / Transitions /
Set Pieces) which are team-relative, this module is scoped to a SINGLE match and
covers EVERY player who featured for EITHER team.  Team affiliation is carried on
each row (``team_name``) and rendered via logo/colour in the component layer.

╔══════════════════════════════════════════════════════════════════════════════╗
║ PHASE 0 — DISCOVERY FINDINGS (documented before implementation)               ║
╠══════════════════════════════════════════════════════════════════════════════╣

A. NAVIGATION & ARCHITECTURE
   • Module selector lives in components/analysis_cards.py :: _module_selector()
     — four _module_card_active() entries with id
     {"type": f"{prefix}-module-card", "index": module_id}.  The switch happens in
     _analysis_view() (same file) keyed on `module`, dispatched by callback #6
     (_update_sections) in callbacks/analysis_callbacks.py :: _register_prefix().
     Adding "Player Analysis" = (1) a 5th _module_card_active(... "player" ...),
     (2) a branch in _analysis_view() rendering our card, (3) "player" added to the
     active_module tuple test in _update_sections.
   • Match prefix is "ma" (Match Analysis).  Opponent Analysis uses "opponent"
     plus an "opp-season-" namespace.
   • Raw match events are loaded via _load_match_events(match_csv) in
     analytics/goalkeeper_buildup.py (pd.read_csv + Opta→dashboard rename).  That
     load point is NOT cached.  We add our own cache layer here keyed on the CSV
     path + mtime so PV/KPI computation is not repeated on every tab switch.
   • Existing "Player Analysis tab" — tabs/player_analysis.py :: layout() /
     render_player_content() — is an OLDER, separate top-level artifact viewer
     wired into tabs_callbacks.py (tab == "tab-player").  It is LEFT UNTOUCHED.
     This module is fully independent and lives inside Match Analysis only.
   • match_report.py still exists in tabs/ but is NOT imported here; all lineup /
     substitution / minutes logic below is reimplemented fresh.

B. PV ENGINE  (utils/pv_model.py :: PossessionValueModel — ML model ONLY)
   • get_instance(model_path=None) -> singleton
   • score(x, y, type_id=1, outcome=1, **kw) -> float P(goal) ∈ [0,1]
   • delta(x_from, y_from, x_to, y_to, type_id_from=1, type_id_to=1, **kw) -> float
   • pva_sequence(events: list[dict]) -> list[float]  (events need x,y; optional
     type_id, outcome, through_ball, cross, head, aerial; poss_event_index auto)
   • _build_features() maps event context to FEATURE_COLS:
       is_pass=int(type_id==1), is_carry_touch=int(type_id==44),
       is_recovery=int(type_id==49), is_tackle=int(type_id==7),
       is_interception=int(type_id==8); plus through_ball/cross/head/aerial kwargs.
     => Defensive actions ARE scored with their event identity by passing the
        correct type_id (7=tackle, 8=interception, 49=recovery), not as generic
        ball-location events.
   • player_name AND player_id are present on raw rows; we key on player_name
     (matches the rest of the codebase; player_id kept for disambiguation).
   • Legacy get_pv_model()/get_xt_zone() are NOT used anywhere here (deliberate).

   PV CONVENTION FOR THIS MODULE (academic definition):
   • Offensive PVA  = sum of per-event PVA for a player's ON-BALL attacking actions
     (passes, carries/touches, take-ons, crosses, shots) — i.e. value the player
     ADDED while their team had the ball, via pva_sequence() over each possession.
   • Defensive PVA  = value generated by a player's OUT-OF-POSSESSION actions
     (tackle / interception / ball recovery / clearance / blocked pass), scored as
     score(x, y, type_id=<defensive id>) — the goal probability the action denies
     the opponent at that location.  Higher P(goal) location => more valuable stop.
     This is a positive quantity (a regain HIGH up the pitch is worth more).
   • Total PVA = Offensive + Defensive.

C. KPI FEASIBILITY  (full table — see module-level KPI_DEFINITIONS dict)
   DIRECT   = Opta event type / qualifier column.
   REUSE    = existing codebase function.
   NEW      = new convention defined here (documented inline).
   EXCLUDE  = ambiguous / underivable — see EXCLUDED_KPIS.

D. MINUTES PLAYED  (per-match, this module only)
   • Substitutions: event "Player Off" (type_id 18) / "Player on" (type_id 19),
     timestamped by time_min.  Dismissals: event "Card" (type_id 17) with
     "Second yellow"=="Si" OR "Red Card"=="Si".
   • Match full-time minute = max time_min over period-2 (and beyond) "End"
     (type_id 30) events — data-driven, captures stoppage time (e.g. 94').
   • Starting XI = first 11 distinct players per team to record an on-ball event
     before any "Player on" for that team (robust: setup rows carry no player).
   • minutes(player) = (off_min or dismiss_min or full_time) − (on_min or 0),
     clamped to [0, full_time].

E. STYLING & COMPONENTS
   • Pitch: styling/pitch_utils.py :: draw_pitch(fig, theme="dark", half=None, ...).
   • Table: components/tables.py :: create_datatable(df, table_id, title, page_size).
   • KPI card: components/kpis.py :: kpi_card(title, value, subtitle, icon, color).
     (mini_kpi() does NOT exist — we use kpi_card for highlights.)
   • Modal: styling/ui_components.py :: build_unified_modal(modal_id, title_id,
     body_id, title, size, body).
   • Chain visual: components/buildup_cards.py :: _chain_event_node()/_chain_connector()
     — re-used as the visual basis for the Possession Sequence Viewer.
╚══════════════════════════════════════════════════════════════════════════════╝
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd

from src.analytics.general_buildup import build_possessions
from src.analytics.goalkeeper_buildup import _load_match_events
from src.team_mapping import canonical_name
from src.utils.caching import cache_get, cache_set
from src.utils.pv_model import PossessionValueModel

log = logging.getLogger("dashboard.player_analysis")


# ═══════════════════════════════════════════════════════════════════════════════
# CACHE VERSIONING
# ═══════════════════════════════════════════════════════════════════════════════
# Bump _PIPELINE_VERSION whenever the PV scoring / KPI computation logic in this
# module changes, so cached bundles computed under the old logic are invalidated.
# We ALSO fold in the model file's (mtime, size) so a re-trained / re-packaged
# model invalidates the cache automatically — and, critically, so a cache entry
# computed while the model FAILED to load (sklearn missing → all scores 0.0) is
# never silently served after the model starts loading correctly.  Without this,
# a real fix can appear "not to work" because a stale 0.0 bundle is returned.
_PIPELINE_VERSION = "pv2"


def _pv_cache_token() -> str:
    """A short token that changes when the model file or pipeline version changes."""
    try:
        from src.utils.pv_model import _DEFAULT_MODEL_PATH
        st = Path(_DEFAULT_MODEL_PATH).stat()
        model_sig = f"{int(st.st_mtime)}-{st.st_size}"
    except Exception:
        model_sig = "nomodel"
    # Whether the model actually loaded also belongs in the token: a bundle built
    # with a loaded model must never collide with one built without it.
    try:
        loaded = int(PossessionValueModel.get_instance()._loaded)
    except Exception:
        loaded = 0
    return f"{_PIPELINE_VERSION}-{model_sig}-l{loaded}"


# ═══════════════════════════════════════════════════════════════════════════════
# CONSTANTS & CONVENTIONS
# ═══════════════════════════════════════════════════════════════════════════════

# Opta type_ids (verified against raw CSV).
TID_PASS         = 1
TID_TAKE_ON      = 3
TID_TACKLE       = 7
TID_INTERCEPTION = 8
TID_CLEARANCE    = 12
TID_MISS         = 13
TID_POST         = 14
TID_SAVED_SHOT   = 15
TID_GOAL         = 16
TID_CARD         = 17
TID_PLAYER_OFF   = 18
TID_PLAYER_ON    = 19
TID_END          = 30
TID_AERIAL       = 44
TID_BALL_RECOV   = 49
TID_BLOCKED_PASS = 74

SHOT_TYPE_IDS = frozenset({TID_MISS, TID_POST, TID_SAVED_SHOT, TID_GOAL})

# On-ball offensive event types (lowercase event names) scored for Offensive PVA.
OFFENSIVE_EVENTS = frozenset({
    "pass", "ball touch", "take on", "goal", "miss", "saved shot",
    "post", "attempt saved", "shot on post", "dispossessed", "offside pass",
})

# Out-of-possession defensive actions scored for Defensive PVA / Out KPIs.
DEFENSIVE_EVENTS = frozenset({
    "tackle", "interception", "ball recovery", "clearance",
    "blocked pass", "challenge", "aerial",
})

# Map event name -> Opta type_id so PV scoring carries the event identity.
EVENT_TO_TID = {
    "pass": TID_PASS,
    "ball touch": TID_AERIAL,         # touch ≈ carry/touch feature
    "take on": TID_TAKE_ON,
    "tackle": TID_TACKLE,
    "interception": TID_INTERCEPTION,
    "ball recovery": TID_BALL_RECOV,
    "clearance": TID_CLEARANCE,
    "blocked pass": TID_BLOCKED_PASS,
    "aerial": TID_AERIAL,
    "goal": TID_GOAL,
    "miss": TID_MISS,
    "saved shot": TID_SAVED_SHOT,
    "post": TID_POST,
}

# Per-90 normalisation cutoff — JUDGMENT CALL (documented in summary):
# players with < MIN_MINUTES_FOR_PER90 are flagged (kept but greyed in charts),
# never silently dropped, so the underlying numbers remain visible.
MIN_MINUTES_FOR_PER90 = 20.0

# Switch of Play (NEW convention): a pass whose start/end y span the pitch width
# across non-adjacent corridors (L<->R) covering >= SWITCH_MIN_WIDTH of the width.
# We prefer the Opta "Switch of play" qualifier when present (DIRECT) and fall
# back to this geometric rule only if the qualifier column is absent.
SWITCH_MIN_WIDTH = 40.0   # Opta y-units (0-100)

# Line Break (NEW convention): a completed forward pass that crosses one of the
# vertical thirds boundaries (x = 33.33 or 66.67) moving up-pitch, advancing the
# ball by >= LINE_BREAK_MIN_DX in x.  "Attempted" = same forward geometry on any
# pass; "Completed" = outcome == 1.
LINE_BREAK_BOUNDARIES = (33.33, 66.67)
LINE_BREAK_MIN_DX = 8.0

# Ball Progression (NEW convention): an on-ball action (pass or carry/touch/take-on)
# that advances the ball toward goal by >= PROGRESSION_MIN_DX in x.  Aligned with
# the spirit of general_buildup forward-progression but scoped to per-player counts.
PROGRESSION_MIN_DX = 10.0

# Cross qualifier columns (DIRECT) — reuses the exact qualifier the PV/CC layer reads.
CROSS_QUAL_COLS = ("Cross", "cross")
THROUGH_QUAL_COLS = ("Through ball", "through_ball")
SWITCH_QUAL_COLS = ("Switch of play", "switch_of_play")
HEAD_QUAL_COLS = ("Head pass", "head_pass", "Head")


# ═══════════════════════════════════════════════════════════════════════════════
# KPI DEFINITIONS  (for academic defensibility — surfaced via info-icon modals)
# Each entry: (label, classification, one-line definition).
# ═══════════════════════════════════════════════════════════════════════════════

KPI_DEFINITIONS: Dict[str, Dict[str, str]] = {
    # ── In Possession ──
    "passes_attempted":   {"class": "DIRECT", "def": "Count of events of type 'Pass' by the player."},
    "passes_completed":   {"class": "DIRECT", "def": "Passes with outcome = 1 (successful)."},
    "pass_completion_pct":{"class": "DIRECT", "def": "Passes Completed ÷ Passes Attempted × 100."},
    "switches_of_play":   {"class": "DIRECT", "def": "Passes flagged with the Opta 'Switch of play' qualifier (geometric fallback: completed pass spanning ≥40 width units across opposite corridors)."},
    "crosses_attempted":  {"class": "DIRECT", "def": "Passes flagged with the Opta 'Cross' qualifier."},
    "crosses_completed":  {"class": "DIRECT", "def": "Crosses with outcome = 1."},
    "line_breaks_attempted": {"class": "NEW", "def": "Forward passes that cross a vertical-third boundary (x=33.3 or 66.7) advancing ≥8 x-units up-pitch."},
    "line_breaks_completed": {"class": "NEW", "def": "Line-break passes with outcome = 1."},
    "line_break_pct":     {"class": "NEW", "def": "Line Breaks Completed ÷ Line Breaks Attempted × 100."},
    "ball_progressions":  {"class": "NEW", "def": "On-ball actions (pass/carry/take-on) advancing the ball ≥10 x-units toward goal, outcome = 1."},
    "take_ons":           {"class": "DIRECT", "def": "Count of events of type 'Take On' by the player."},
    "attempts_at_goal":   {"class": "DIRECT", "def": "Shots: events of type Miss/Post/Saved Shot/Goal (type_id 13–16)."},
    "goals":              {"class": "DIRECT", "def": "Events of type 'Goal' (type_id 16)."},
    # ── Out of Possession ──
    "tackles_made":       {"class": "DIRECT", "def": "Count of events of type 'Tackle' by the player."},
    "tackles_won":        {"class": "DIRECT", "def": "Tackles with outcome = 1 (possession retained)."},
    "blocks":             {"class": "DIRECT", "def": "Events of type 'Blocked Pass' (type_id 74)."},
    "interceptions":      {"class": "DIRECT", "def": "Events of type 'Interception' (type_id 8)."},
    "clearances":         {"class": "DIRECT", "def": "Events of type 'Clearance' (type_id 12)."},
    "aerial_duels_won":   {"class": "DIRECT", "def": "Aerial events (type_id 44) with outcome = 1."},
    "aerial_duels_total": {"class": "DIRECT", "def": "All Aerial events (type_id 44) contested by the player."},
    "possession_regains": {"class": "REUSE",  "def": "High regains in the attacking third (x≥66.7, open play) — detect_high_regains() in high_regains.py."},
}

# KPIs deliberately EXCLUDED — ambiguous / not standard Opta / underivable.
# Listed prominently in the final summary; needs Riccardo's definition to add.
EXCLUDED_KPIS = {
    "Step-Ins": "Not a standard Opta term; may overlap with carries/progressions. Need a definition (e.g. a carry stepping into the next third?).",
    "Pressing Direct": "defensive_pressing.py classifies pressing by corridor/zone at TEAM level, not per-player 'direct vs indirect'. No player-level direct/indirect split is defined.",
    "Pressing Indirect": "Same as above — no defensible per-player indirect-pressing definition available.",
    "Physical Duels Won": "No distinct ground-duel event separate from Tackle/Challenge; 'physical duel' is ambiguous vs aerial/tackle.",
    "Possession Contests Won": "Not a standard Opta term; overlaps with tackles won + aerials won. Need an explicit definition to avoid double counting.",
    "Loose Ball Receptions": "No clean event marks a 'loose ball reception' distinct from Ball recovery / Ball touch. Need a definition.",
    "Pushing On": "Not a standard Opta term; ambiguous (off-ball movement not captured in event data).",
    "Pushing On into Pressing": "Same as 'Pushing On' — off-ball, not in event data.",
    "Possession Interrupted": "Ambiguous — overlaps with interceptions/regains. Need a definition distinct from those.",
}


# ═══════════════════════════════════════════════════════════════════════════════
# QUALIFIER HELPER
# ═══════════════════════════════════════════════════════════════════════════════

def _has_qual(row: pd.Series, *cols: str) -> bool:
    """True if any of the named qualifier columns is truthy ('Si'/'Yes'/1/True)."""
    for c in cols:
        v = str(row.get(c, "")).strip().lower()
        if v in ("si", "yes", "1", "true"):
            return True
    return False


# ═══════════════════════════════════════════════════════════════════════════════
# MATCH LOADING (cached) + POSSESSION ASSIGNMENT
# ═══════════════════════════════════════════════════════════════════════════════

def _load_match_cached(match_csv: Path) -> pd.DataFrame:
    """Load + possession-tag a match once; cache by path + mtime."""
    p = Path(match_csv)
    try:
        mtime = p.stat().st_mtime
    except OSError:
        mtime = 0
    key = f"pa_match_{p.stem}_{mtime}_{_pv_cache_token()}"
    cached = cache_get(key)
    if cached is not None:
        return cached

    df = _load_match_events(p)
    if df is None or df.empty:
        return pd.DataFrame()

    # build_possessions needs event_type/team_id/period/team_name (all present after load).
    df = build_possessions(df)
    cache_set(key, df)
    return df


# ═══════════════════════════════════════════════════════════════════════════════
# MINUTES PLAYED (Phase 0D)
# ═══════════════════════════════════════════════════════════════════════════════

def _match_full_time(df: pd.DataFrame) -> float:
    """Data-driven full-time minute (captures stoppage time)."""
    ends = df[(df["type_id"] == TID_END) & (df["period"].fillna(0) >= 2)]
    if not ends.empty:
        return float(ends["minute"].max())
    # Fallback: max minute seen.
    return float(df["minute"].fillna(0).max() or 90.0)


def compute_minutes_played(df: pd.DataFrame) -> Dict[str, Dict[str, Any]]:
    """
    Per-player minutes for a single match.

    Returns {player_name: {"minutes": float, "team": str, "started": bool,
                           "on": float|None, "off": float|None}}.
    """
    full_time = _match_full_time(df)
    out: Dict[str, Dict[str, Any]] = {}

    subs_on  = df[df["type_id"] == TID_PLAYER_ON]
    subs_off = df[df["type_id"] == TID_PLAYER_OFF]
    on_min  = {str(r["player_name"]): float(r["minute"] or 0) for _, r in subs_on.iterrows()
               if pd.notna(r.get("player_name"))}
    off_min = {str(r["player_name"]): float(r["minute"] or 0) for _, r in subs_off.iterrows()
               if pd.notna(r.get("player_name"))}

    # Dismissals (second yellow / red).
    cards = df[df["type_id"] == TID_CARD]
    dismiss_min: Dict[str, float] = {}
    for _, r in cards.iterrows():
        if pd.isna(r.get("player_name")):
            continue
        if _has_qual(r, "Second yellow", "Red Card"):
            dismiss_min[str(r["player_name"])] = float(r["minute"] or full_time)

    # Players who were subbed ON are not starters.
    subbed_on_players = set(on_min.keys())

    # Starting XI per team: first 11 distinct players (by first on-ball event)
    # that were NOT subbed on.
    onball = df[df["player_name"].notna() & df["x"].notna()].sort_values(
        ["period", "minute", "second", "event_id"]
    )
    starters: set = set()
    per_team_count: Dict[str, int] = {}
    for _, r in onball.iterrows():
        name = str(r["player_name"])
        team = str(r.get("team_name", ""))
        if name in subbed_on_players or name in starters:
            continue
        if per_team_count.get(team, 0) >= 11:
            continue
        starters.add(name)
        per_team_count[team] = per_team_count.get(team, 0) + 1

    # Team affiliation per player (last seen team_name on an on-ball event).
    player_team: Dict[str, str] = {}
    for _, r in onball.iterrows():
        if pd.notna(r.get("player_name")):
            player_team[str(r["player_name"])] = str(r.get("team_name", ""))

    all_players = set(player_team.keys()) | subbed_on_players
    for name in all_players:
        start = on_min.get(name, 0.0) if name in subbed_on_players else 0.0
        end_candidates = [full_time]
        if name in off_min:
            end_candidates.append(off_min[name])
        if name in dismiss_min:
            end_candidates.append(dismiss_min[name])
        end = min(end_candidates)
        minutes = max(0.0, min(end - start, full_time))
        out[name] = {
            "minutes": round(minutes, 1),
            "team": player_team.get(name, ""),
            "started": name in starters,
            "on": on_min.get(name),
            "off": off_min.get(name),
            "dismissed": name in dismiss_min,
        }
    return out


# ═══════════════════════════════════════════════════════════════════════════════
# POSSESSION VALUE (Phase 1)
# ═══════════════════════════════════════════════════════════════════════════════

def _event_kwargs(row: pd.Series) -> Dict[str, int]:
    """Qualifier kwargs for PV scoring from a raw row."""
    return {
        "through_ball": int(_has_qual(row, *THROUGH_QUAL_COLS)),
        "cross": int(_has_qual(row, *CROSS_QUAL_COLS)),
        "head": int(_has_qual(row, *HEAD_QUAL_COLS)),
        "aerial": int(str(row.get("event_type", "")).strip().lower() == "aerial"),
    }


def compute_player_pva(df: pd.DataFrame, pv: PossessionValueModel) -> pd.DataFrame:
    """
    Per-player Offensive / Defensive / Total PVA for the match.

    Offensive PVA: pva_sequence() over each possession's on-ball events, summed by
    the acting player.  Defensive PVA: score() at the defensive action's location
    (type_id-aware), summed by the acting player.

    Returns a DataFrame: player_name, team_name, off_pva, def_pva, total_pva.
    """
    off_acc: Dict[str, float] = {}
    def_acc: Dict[str, float] = {}
    team_of: Dict[str, str] = {}

    # ── Offensive PVA: per-possession sequence deltas ──
    for poss_id, grp in df.groupby("poss_id"):
        grp = grp.sort_values(["period", "minute", "second", "event_id"])
        events = []
        rows = []
        for _, r in grp.iterrows():
            et = str(r.get("event_type", "")).strip().lower()
            if et not in OFFENSIVE_EVENTS:
                continue
            if pd.isna(r.get("x")) or pd.isna(r.get("y")):
                continue
            kw = _event_kwargs(r)
            events.append({
                "x": float(r["x"]), "y": float(r["y"]),
                "type_id": int(EVENT_TO_TID.get(et, TID_PASS)),
                "outcome": int(r.get("outcome", 1) or 0),
                **kw,
            })
            rows.append(r)
        if not events:
            continue
        pva = pv.pva_sequence(events)
        for r, d in zip(rows, pva):
            name = str(r.get("player_name", "")).strip()
            if not name or name == "nan":
                continue
            off_acc[name] = off_acc.get(name, 0.0) + float(d)
            team_of.setdefault(name, str(r.get("team_name", "")))

    # ── Defensive PVA: location value of out-of-possession actions ──
    for _, r in df.iterrows():
        et = str(r.get("event_type", "")).strip().lower()
        if et not in DEFENSIVE_EVENTS:
            continue
        # Aerials count on both sides; here we only count successful defensive aerials.
        if et == "aerial" and int(r.get("outcome", 0) or 0) != 1:
            continue
        if pd.isna(r.get("x")) or pd.isna(r.get("y")):
            continue
        name = str(r.get("player_name", "")).strip()
        if not name or name == "nan":
            continue
        tid = EVENT_TO_TID.get(et, TID_BALL_RECOV)
        val = pv.score(float(r["x"]), float(r["y"]), type_id=tid,
                       outcome=int(r.get("outcome", 1) or 0))
        def_acc[name] = def_acc.get(name, 0.0) + float(val)
        team_of.setdefault(name, str(r.get("team_name", "")))

    players = set(off_acc) | set(def_acc)
    recs = []
    for name in players:
        off_v = round(off_acc.get(name, 0.0), 4)
        def_v = round(def_acc.get(name, 0.0), 4)
        recs.append({
            "player_name": name,
            "team_name": team_of.get(name, ""),
            "off_pva": off_v,
            "def_pva": def_v,
            "total_pva": round(off_v + def_v, 4),
        })
    res = pd.DataFrame(recs)
    if not res.empty:
        res = res.sort_values("total_pva", ascending=False).reset_index(drop=True)
    return res


def compute_event_pv_map(df: pd.DataFrame, pv: PossessionValueModel) -> pd.DataFrame:
    """
    Per-event PV delta for the full-match event map.

    For on-ball offensive events the delta comes from pva_sequence within the
    possession (value added by that action).  Returns: player_name, team_name,
    minute, event_type, x, y, pv_delta.
    """
    recs: List[dict] = []
    for poss_id, grp in df.groupby("poss_id"):
        grp = grp.sort_values(["period", "minute", "second", "event_id"])
        events, rows = [], []
        for _, r in grp.iterrows():
            et = str(r.get("event_type", "")).strip().lower()
            if et not in OFFENSIVE_EVENTS:
                continue
            if pd.isna(r.get("x")) or pd.isna(r.get("y")):
                continue
            events.append({
                "x": float(r["x"]), "y": float(r["y"]),
                "type_id": int(EVENT_TO_TID.get(et, TID_PASS)),
                "outcome": int(r.get("outcome", 1) or 0),
                **_event_kwargs(r),
            })
            rows.append(r)
        if not events:
            continue
        pva = pv.pva_sequence(events)
        for r, d in zip(rows, pva):
            name = str(r.get("player_name", "")).strip()
            if not name or name == "nan":
                continue
            recs.append({
                "player_name": name,
                "team_name": str(r.get("team_name", "")),
                "minute": int(r.get("minute", 0) or 0),
                "event_type": str(r.get("event_type", "")).title(),
                "x": float(r["x"]), "y": float(r["y"]),
                "pv_delta": round(float(d), 4),
            })
    return pd.DataFrame(recs)


def compute_possession_swings(df: pd.DataFrame, pv: PossessionValueModel) -> pd.DataFrame:
    """
    Rank possessions by net swing.

    JUDGMENT CALL (documented): swing = SUM of |PVA| across the possession's
    on-ball actions.  Rationale: a possession's "story" is the total value churned
    through the chain (a long build-up culminating in a chance), not just the single
    biggest jump — sum-of-absolute rewards multi-action sequences which are the most
    analytically interesting to inspect in the sequence viewer.

    Returns: poss_id, team_name, start_min, n_events, swing (sorted desc).
    """
    recs = []
    for poss_id, grp in df.groupby("poss_id"):
        grp = grp.sort_values(["period", "minute", "second", "event_id"])
        events = []
        for _, r in grp.iterrows():
            et = str(r.get("event_type", "")).strip().lower()
            if et not in OFFENSIVE_EVENTS:
                continue
            if pd.isna(r.get("x")) or pd.isna(r.get("y")):
                continue
            events.append({
                "x": float(r["x"]), "y": float(r["y"]),
                "type_id": int(EVENT_TO_TID.get(et, TID_PASS)),
                "outcome": int(r.get("outcome", 1) or 0),
                **_event_kwargs(r),
            })
        if len(events) < 2:
            continue
        pva = pv.pva_sequence(events)
        swing = float(np.sum(np.abs(pva)))
        first = grp.iloc[0]
        team = str(grp["team_name"].dropna().iloc[0]) if grp["team_name"].notna().any() else ""
        recs.append({
            "poss_id": int(poss_id),
            "team_name": team,
            "start_min": int(first.get("minute", 0) or 0),
            "n_events": len(events),
            "swing": round(swing, 4),
        })
    res = pd.DataFrame(recs)
    if not res.empty:
        res = res.sort_values("swing", ascending=False).reset_index(drop=True)
    return res


def build_possession_sequence(df: pd.DataFrame, poss_id: int,
                              pv: PossessionValueModel) -> Dict[str, Any]:
    """
    Build the node/connector + cumulative-PV data for one possession.

    Uses pva_sequence() (NOT a hand-rolled accumulation loop).  Returns:
      {"nodes": [{player, event_type, x, y, pva, is_team, cum}], "team_name": str}
    where 'is_team' marks the possession-owning team for colour, and 'cum' is the
    running cumulative PV.
    """
    grp = df[df["poss_id"] == poss_id].sort_values(
        ["period", "minute", "second", "event_id"]
    )
    if grp.empty:
        return {"nodes": [], "team_name": ""}

    poss_team = str(grp["team_name"].dropna().iloc[0]) if grp["team_name"].notna().any() else ""
    events, rows = [], []
    for _, r in grp.iterrows():
        et = str(r.get("event_type", "")).strip().lower()
        if et not in OFFENSIVE_EVENTS:
            continue
        if pd.isna(r.get("x")) or pd.isna(r.get("y")):
            continue
        events.append({
            "x": float(r["x"]), "y": float(r["y"]),
            "type_id": int(EVENT_TO_TID.get(et, TID_PASS)),
            "outcome": int(r.get("outcome", 1) or 0),
            **_event_kwargs(r),
        })
        rows.append(r)

    if not events:
        return {"nodes": [], "team_name": poss_team}

    pva = pv.pva_sequence(events)
    cum = float(np.cumsum(pva)[-1]) if pva else 0.0
    running = 0.0
    nodes = []
    for r, d in zip(rows, pva):
        running += float(d)
        nodes.append({
            "player": str(r.get("player_name", "?")),
            "event_type": str(r.get("event_type", "")),
            "x": float(r["x"]), "y": float(r["y"]),
            "pva": round(float(d), 4),
            "minute": int(r.get("minute", 0) or 0),
            "is_team": canonical_name(str(r.get("team_name", ""))) == canonical_name(poss_team),
            "cum": round(running, 4),
        })
    return {"nodes": nodes, "team_name": poss_team, "total": round(cum, 4)}


# ═══════════════════════════════════════════════════════════════════════════════
# KPI COMPUTATION (Phase 2 + 3)
# ═══════════════════════════════════════════════════════════════════════════════

def _is_line_break(row: pd.Series) -> bool:
    """NEW: forward pass crossing a vertical-third boundary, ≥ LINE_BREAK_MIN_DX."""
    x0 = row.get("x"); x1 = row.get("pass_end_x")
    if pd.isna(x0) or pd.isna(x1):
        return False
    x0, x1 = float(x0), float(x1)
    if x1 - x0 < LINE_BREAK_MIN_DX:
        return False
    for b in LINE_BREAK_BOUNDARIES:
        if x0 < b <= x1:
            return True
    return False


def _is_progression(row: pd.Series) -> bool:
    """NEW: on-ball action advancing the ball ≥ PROGRESSION_MIN_DX toward goal."""
    x0 = row.get("x"); x1 = row.get("pass_end_x")
    if pd.isna(x0) or pd.isna(x1):
        return False
    return (float(x1) - float(x0)) >= PROGRESSION_MIN_DX


def _is_switch(row: pd.Series) -> bool:
    """DIRECT (qualifier) with geometric fallback."""
    if _has_qual(row, *SWITCH_QUAL_COLS):
        return True
    y0 = row.get("y"); y1 = row.get("pass_end_y")
    if pd.isna(y0) or pd.isna(y1):
        return False
    return abs(float(y1) - float(y0)) >= SWITCH_MIN_WIDTH


def compute_in_possession_kpis(df: pd.DataFrame, regains_by_player: Dict[str, int]) -> pd.DataFrame:
    """Per-player In-Possession KPI table (only DIRECT/REUSE/NEW columns)."""
    recs: Dict[str, Dict[str, Any]] = {}

    def _row(name, team):
        if name not in recs:
            recs[name] = {
                "player_name": name, "team_name": team,
                "passes_attempted": 0, "passes_completed": 0,
                "switches_of_play": 0, "crosses_attempted": 0, "crosses_completed": 0,
                "line_breaks_attempted": 0, "line_breaks_completed": 0,
                "ball_progressions": 0, "take_ons": 0,
                "attempts_at_goal": 0, "goals": 0,
            }
        return recs[name]

    for _, r in df.iterrows():
        name = str(r.get("player_name", "")).strip()
        if not name or name == "nan":
            continue
        team = str(r.get("team_name", ""))
        et = str(r.get("event_type", "")).strip().lower()
        tid = r.get("type_id")
        succ = int(r.get("outcome", 0) or 0) == 1
        rec = _row(name, team)

        if et == "pass":
            rec["passes_attempted"] += 1
            if succ:
                rec["passes_completed"] += 1
            if _is_switch(r):
                rec["switches_of_play"] += 1
            if _has_qual(r, *CROSS_QUAL_COLS):
                rec["crosses_attempted"] += 1
                if succ:
                    rec["crosses_completed"] += 1
            if _is_line_break(r):
                rec["line_breaks_attempted"] += 1
                if succ:
                    rec["line_breaks_completed"] += 1
            if succ and _is_progression(r):
                rec["ball_progressions"] += 1
        elif et == "take on":
            rec["take_ons"] += 1
            if succ and _is_progression(r):
                rec["ball_progressions"] += 1

        if tid in SHOT_TYPE_IDS or et in ("goal", "miss", "saved shot", "post"):
            rec["attempts_at_goal"] += 1
            if et == "goal" or tid == TID_GOAL:
                rec["goals"] += 1

    out = pd.DataFrame(list(recs.values()))
    if out.empty:
        return out
    out["pass_completion_pct"] = np.where(
        out["passes_attempted"] > 0,
        (out["passes_completed"] / out["passes_attempted"] * 100).round(1), 0.0,
    )
    out["line_break_pct"] = np.where(
        out["line_breaks_attempted"] > 0,
        (out["line_breaks_completed"] / out["line_breaks_attempted"] * 100).round(1), 0.0,
    )
    out["possession_regains"] = out["player_name"].map(regains_by_player).fillna(0).astype(int)
    return out


def compute_out_possession_kpis(df: pd.DataFrame, regains_by_player: Dict[str, int]) -> pd.DataFrame:
    """Per-player Out-of-Possession KPI table (only DIRECT/REUSE columns)."""
    recs: Dict[str, Dict[str, Any]] = {}

    def _row(name, team):
        if name not in recs:
            recs[name] = {
                "player_name": name, "team_name": team,
                "tackles_made": 0, "tackles_won": 0, "blocks": 0,
                "interceptions": 0, "clearances": 0,
                "aerial_duels_won": 0, "aerial_duels_total": 0,
            }
        return recs[name]

    for _, r in df.iterrows():
        name = str(r.get("player_name", "")).strip()
        if not name or name == "nan":
            continue
        team = str(r.get("team_name", ""))
        et = str(r.get("event_type", "")).strip().lower()
        succ = int(r.get("outcome", 0) or 0) == 1
        rec = _row(name, team)

        if et == "tackle":
            rec["tackles_made"] += 1
            if succ:
                rec["tackles_won"] += 1
        elif et == "blocked pass":
            rec["blocks"] += 1
        elif et == "interception":
            rec["interceptions"] += 1
        elif et == "clearance":
            rec["clearances"] += 1
        elif et == "aerial":
            rec["aerial_duels_total"] += 1
            if succ:
                rec["aerial_duels_won"] += 1

    out = pd.DataFrame(list(recs.values()))
    if out.empty:
        return out
    out["possession_regains"] = out["player_name"].map(regains_by_player).fillna(0).astype(int)
    return out


def compute_regains_by_player(df: pd.DataFrame, teams: List[str]) -> Dict[str, int]:
    """REUSE detect_high_regains() for both teams; count by acting player."""
    from src.analytics.high_regains import detect_high_regains
    counts: Dict[str, int] = {}
    for team in teams:
        try:
            regains = detect_high_regains(df, team)
        except Exception as exc:
            log.debug("detect_high_regains failed for %s: %s", team, exc)
            continue
        if regains is None or regains.empty:
            continue
        pcol = "player_name" if "player_name" in regains.columns else None
        if not pcol:
            continue
        for name, c in regains[pcol].dropna().value_counts().items():
            counts[str(name)] = counts.get(str(name), 0) + int(c)
    return counts


# ═══════════════════════════════════════════════════════════════════════════════
# TOP-LEVEL ORCHESTRATION (cached bundle for the whole module)
# ═══════════════════════════════════════════════════════════════════════════════

def analyse_player_analysis(match_csv: Path) -> Dict[str, Any]:
    """
    Compute the full Player Analysis bundle for a match (cached).

    Returns a dict consumed by the component layer:
      teams, full_time, minutes, pva (DataFrame), event_map (DataFrame),
      swings (DataFrame), in_possession (DataFrame), out_possession (DataFrame),
      df (possession-tagged events for the sequence viewer).
    """
    p = Path(match_csv)
    try:
        mtime = p.stat().st_mtime
    except OSError:
        mtime = 0
    bundle_key = f"pa_bundle_{p.stem}_{mtime}_{_pv_cache_token()}"
    cached = cache_get(bundle_key)
    if cached is not None:
        return cached

    df = _load_match_cached(p)
    if df.empty:
        empty = {"teams": [], "df": df, "minutes": {}, "full_time": 90.0,
                 "pva": pd.DataFrame(), "event_map": pd.DataFrame(),
                 "swings": pd.DataFrame(), "in_possession": pd.DataFrame(),
                 "out_possession": pd.DataFrame()}
        return empty

    pv = PossessionValueModel.get_instance()
    teams = [t for t in df["team_name"].dropna().unique().tolist() if str(t).strip()]

    minutes = compute_minutes_played(df)
    pva = compute_player_pva(df, pv)
    event_map = compute_event_pv_map(df, pv)
    swings = compute_possession_swings(df, pv)
    regains = compute_regains_by_player(df, teams)
    in_kpis = compute_in_possession_kpis(df, regains)
    out_kpis = compute_out_possession_kpis(df, regains)

    bundle = {
        "teams": teams,
        "df": df,
        "minutes": minutes,
        "full_time": _match_full_time(df),
        "pva": pva,
        "event_map": event_map,
        "swings": swings,
        "in_possession": in_kpis,
        "out_possession": out_kpis,
    }
    cache_set(bundle_key, bundle)
    return bundle
